server:
  port: 8070

eureka:
  client:
    service-url:
      #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔。
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: service-gateway
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册

#--------------------Zuul-----------------------
zuul:
  routes:
    #/api-a/ 开头匹配到service-producer
    api-a:
      path: /api-a/**
      serviceId: service-producer
    #/api-b/ 开头匹配到service-producer
    api-b:
      path: /api-b/**
      serviceId: service-producer
    #匹配/github/直接重定向到https://github.com/
    github:
      path: /github/**
      url: https://github.com/
    member:
      path: /member/**
      serviceId: service-member
      sensitiveHeaders: "*"
    service-demo:
        path: /service-demo/**
        serviceId: service-demo
    auth:
      path: /auth/**
      serviceId: auth-server
      sensitiveHeaders: "*"
  retryable: false
  ignored-services: "*"
  ribbon:
    eager-load:
      enabled: true
  host:
    connect-timeout-millis: 3000
    socket-timeout-millis: 3000
  add-proxy-headers: true


#---------------------OAuth2---------------------
security:
  oauth2:
    client:
      access-token-uri: http://localhost:${server.port}/auth/oauth/token
      user-authorization-uri: http://localhost:${server.port}/auth/oauth/authorize
      client-id: web
    resource:
      user-info-uri:  http://localhost:${server.port}/auth/api/member
      prefer-token-info: false

#----------------------超时配置-------------------
ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  eureka:
    enabled: true
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 3500